[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "python312"]

[phases.install]
cmds = [
  "npm i",
  "(cd frontend && npm install)",
  "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py --user",
  "python3 -m pip install --user -r requirements.txt",
  "rm get-pip.py"
]

[phases.build]
cmds = [
  "npm run build"
]
