[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "python312"]

[phases.install]
cmds = [
  "npm i",
  "cd frontend && npm install",
  "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]
